spring:
  datasource:
    url: jdbc:mysql://112.74.33.126:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&useAffectedRows=true
    username: root
    password: sxt.2018
server:
  port: 8018